import 'reset-css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import 'material-icons/css/material-icons.scss';
// import 'mmenu-js';
// import 'mmenu-js/src/mmenu.scss';
import '../../scss/fonts.scss';
import '../../scss/common.scss';
import '../../blocks/top-line/top-line';
import '../../components/widgets/header-socials/header-socials';
import '../../components/widgets/sign-in/sign-in';
import '../../components/widgets/choose-language/choose-language';
import '../../blocks/header-form/header-form';
import '../../components/header/header';
import '../../components/logo/logo';
import '../../components/main-nav/main-nav';
import '../../components/widgets/header-search/header-search';
import '../../components/hamburger/hamburger';
import '../../components/mmenu/mmenu';
import '../../components/inspiration/inspiration';
import '../../components/heading/heading';
